#!/usr/bin/env bash
# scripts/build.sh — canonical build/validate entrypoint for the Recipe App.
#
# This is THE single source of truth for what "a build" means for this repo.
# Any flag, check, or sequencing that matters belongs here — never inline in
# CI yaml, ad-hoc commands, or individual dev environments.
#
# Modes:
#   ./scripts/build.sh            — full: lint + test + config validation + clean-tree check
#   ./scripts/build.sh quick      — lint + test only (skips clean-tree check; for pre-commit)
#   ./scripts/build.sh validate   — config validation only (no lint, no tests)
#
# Exit code: 0 on success, non-zero on any failure.
#
# On Windows this CANNOT actually build the IPA (requires a Mac with Xcode).
# The real build happens on Codemagic. This script validates everything the
# Mac runner will need so surprises don't show up post-push.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

MODE="${1:-full}"
FAIL=0

info() { printf '[build] %s\n' "$*"; }
err()  { printf '[build] FAIL: %s\n' "$*" >&2; FAIL=1; }

echo "==================================================================="
echo "  Recipe App build — mode: $MODE"
echo "==================================================================="

# ---------------------------------------------------------------------------
# Step 1: Lint
# ---------------------------------------------------------------------------
if [[ "$MODE" != "validate" ]]; then
    if ! "$REPO_ROOT/scripts/lint.sh"; then
        err "lint failed"
    fi
fi

# ---------------------------------------------------------------------------
# Step 2: Tests
# ---------------------------------------------------------------------------
if [[ "$MODE" != "validate" ]]; then
    if ! "$REPO_ROOT/scripts/test.sh"; then
        err "tests failed"
    fi
fi

# ---------------------------------------------------------------------------
# Step 3: Config validation (all modes)
# ---------------------------------------------------------------------------
info "validating xcodegen project.yml has required fields"
if [[ ! -f "RecipeApp/project.yml" ]]; then
    err "RecipeApp/project.yml missing"
else
    REQUIRED_KEYS=(
        "PRODUCT_BUNDLE_IDENTIFIER: com.seanick80.recipeapp"
        "DEVELOPMENT_TEAM: 3JR8WTJUV6"
        "CODE_SIGN_ENTITLEMENTS: RecipeApp/RecipeApp.entitlements"
    )
    for key in "${REQUIRED_KEYS[@]}"; do
        if ! grep -Fq "$key" RecipeApp/project.yml; then
            err "project.yml missing required setting: $key"
        fi
    done
fi

info "validating entitlements references correct CloudKit container"
if ! grep -Fq "iCloud.com.seanick80.recipeapp" RecipeApp/RecipeApp/RecipeApp.entitlements; then
    err "entitlements file missing CloudKit container iCloud.com.seanick80.recipeapp"
fi

info "validating RecipeAppApp.swift wires CloudKit database"
if ! grep -Fq 'cloudKitDatabase: .private("iCloud.com.seanick80.recipeapp")' RecipeApp/RecipeApp/RecipeAppApp.swift; then
    err "RecipeAppApp.swift ModelConfiguration is missing cloudKitDatabase"
fi

info "validating codemagic.yaml uses ASC API key integration"
if ! grep -Fq "app_store_connect: recipe-app-appstore-key" codemagic.yaml; then
    err "codemagic.yaml missing app_store_connect integration"
fi
if grep -Fq "CODE_SIGNING_ALLOWED=NO" codemagic.yaml; then
    err "codemagic.yaml still has CODE_SIGNING_ALLOWED=NO (remove for device builds)"
fi

info "verifying .xcodeproj is NOT tracked (must be generated by xcodegen)"
if git ls-files --error-unmatch RecipeApp/RecipeApp.xcodeproj 2>/dev/null; then
    err ".xcodeproj is tracked in git — it must be generated by xcodegen, not committed"
fi

# ---------------------------------------------------------------------------
# Step 4: Clean working tree (full mode only)
# ---------------------------------------------------------------------------
if [[ "$MODE" == "full" ]]; then
    info "checking working tree is clean"
    if [[ -n "$(git status --porcelain)" ]]; then
        err "working tree has uncommitted changes — commit or stash before pushing"
        git status --short >&2
    fi
fi

# ---------------------------------------------------------------------------
echo "==================================================================="
if [[ $FAIL -eq 0 ]]; then
    echo "  BUILD OK (mode: $MODE)"
    echo "==================================================================="
    exit 0
else
    echo "  BUILD FAILED (mode: $MODE)" >&2
    echo "===================================================================" >&2
    exit 1
fi
